#!/usr/bin/env bash
# Install desihub packages used by justmospec spectrum simulation
# (desisim templates) and redshift fitting (redrock).
#
# Usage:
#   bash install_desihub.sh
#
# Environment (all optional; the script fills them in when unset):
#   PYTHON                 Interpreter (prefers conda env py312, then python3.12)
#   DESIHUB_SRC            Clone directory for redrock-templates
#   DESIMODEL              Directory that contains desimodel data/
#   DESI_BASIS_TEMPLATES   DESI basis-template directory
#   RR_TEMPLATE_DIR        redrock-templates directory

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DESIHUB_SRC="${DESIHUB_SRC:-${HOME}/desihub}"

pick_python() {
    local c
    if [[ -n "${PYTHON:-}" ]]; then
        echo "${PYTHON}"
        return
    fi
    for c in \
        "${HOME}/.conda/envs/py312/bin/python" \
        "${CONDA_PREFIX:-}/bin/python" \
        python3.12 \
        python3
    do
        [[ -z "${c}" || "${c}" == "/bin/python" ]] && continue
        if [[ "${c}" == /* ]]; then
            [[ -x "${c}" ]] || continue
        else
            command -v "${c}" >/dev/null 2>&1 || continue
            c="$(command -v "${c}")"
        fi
        if "${c}" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)' \
                2>/dev/null; then
            echo "${c}"
            return
        fi
    done
    return 1
}

PYTHON="$(pick_python)" \
    || { echo "error: need Python >= 3.10 (conda env py312 or python3.12)" >&2; exit 1; }
PIP=("${PYTHON}" -m pip)

# Local DESI data used by SpectrumMaker; override by exporting before running.
if [[ -z "${DESIMODEL:-}" ]]; then
    DESIMODEL="/home/Survey/JUST/external/desidata_for_testing_pipeline/desi_data_model"
fi
if [[ -z "${DESI_BASIS_TEMPLATES:-}" ]]; then
    DESI_BASIS_TEMPLATES="/home/Survey/JUST/external/desidata_for_testing_pipeline/desi_spectro_basis/basis_templates/v3.1"
fi
RR_TEMPLATE_DIR="${RR_TEMPLATE_DIR:-${DESIHUB_SRC}/redrock-templates}"

export DESIMODEL DESI_BASIS_TEMPLATES RR_TEMPLATE_DIR

write_env_file() {
    local envfile="${SCRIPT_DIR}/desihub-env.sh"
    cat > "${envfile}" <<EOF
# Generated by install_desihub.sh — source this file before SpectrumMaker.
export DESIMODEL="${DESIMODEL}"
export DESI_BASIS_TEMPLATES="${DESI_BASIS_TEMPLATES}"
export RR_TEMPLATE_DIR="${RR_TEMPLATE_DIR}"
EOF
    echo "==> wrote ${envfile}"
}

have_import() {
    "${PYTHON}" -c "import $1" >/dev/null 2>&1
}

# DESI setup.py files import desiutil, so later packages cannot use isolated builds.
pip_desihub() {
    local repo="$1"
    if have_import "${repo}"; then
        echo "==> ${repo} already installed, skip"
        return
    fi
    echo "==> ${repo}"
    "${PIP[@]}" install --no-build-isolation \
        "git+https://github.com/desihub/${repo}.git"
}

pyver="$("${PYTHON}" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
echo "==> Python ${PYTHON} (${pyver})"

echo "==> PyPI dependencies"
pypi_missing=()
for spec in \
    numpy:numpy \
    scipy:scipy \
    astropy:astropy \
    fitsio:fitsio \
    h5py:h5py \
    numba:numba \
    healpy:healpy \
    pyyaml:yaml \
    requests:requests \
    speclite:speclite
do
    pip_name="${spec%%:*}"
    import_name="${spec##*:}"
    if have_import "${import_name}"; then
        echo "==> ${pip_name} already installed, skip"
    else
        pypi_missing+=("${pip_name}")
    fi
done
if ((${#pypi_missing[@]})); then
    "${PIP[@]}" install "${pypi_missing[@]}"
fi

# Order: desiutil first; desimodel / desitarget feed desispec; those feed desisim.
for repo in desiutil desimodel desitarget desispec desisim redrock; do
    pip_desihub "${repo}"
done

echo "==> redrock-templates -> ${RR_TEMPLATE_DIR}"
if [[ -d "${RR_TEMPLATE_DIR}" ]]; then
    echo "==> redrock-templates already present, skip"
else
    mkdir -p "${DESIHUB_SRC}"
    git clone https://github.com/desihub/redrock-templates "${RR_TEMPLATE_DIR}"
fi

write_env_file

echo
echo "desihub packages installed with ${PYTHON}"
echo "Environment:"
echo "  DESIMODEL=${DESIMODEL}"
echo "  DESI_BASIS_TEMPLATES=${DESI_BASIS_TEMPLATES}"
echo "  RR_TEMPLATE_DIR=${RR_TEMPLATE_DIR}"
echo
echo "In a new shell:  source ${SCRIPT_DIR}/desihub-env.sh"
echo "Then:            pip install -e \".[specsimu]\""
