[build-system]
requires = ["setuptools"]
build-backend = 'setuptools.build_meta'

[project]
name = "just_mospec"
dynamic = ["version"]
authors = [ { name = "Gu Yizhou" } ]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
readme = "README.md"
description = "Spectroscopic Reduction Pipeline for JUST-MOS."
requires-python = ">=3.10"
dependencies = ["numpy", "scipy", "astropy"]
keywords = ["JUST", "MOS", "spectroscopy"]
classifiers = [ "Development Status :: 3 - Alpha",
                "Environment :: Console",
                "Intended Audience :: Science/Research",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3",
                "Topic :: Scientific/Engineering :: Astronomy" ]

[project.optional-dependencies]
test = ["pytest"]
coverage = ["pytest-cov", "coveralls"]
doc = ["Sphinx", "sphinx-rtd-theme"]
specsimu = ["desisim"]

[project.urls]
Repository = "https://github.com/astroyzgu/just_mospec"
Issues = "https://github.com/astroyzgu/just_mospec/issues"

[tool.setuptools]
package-dir = {"" = "py"}

[tool.setuptools.packages.find]
where = ["py"]
exclude = [".github/*"]

[tool.setuptools.dynamic]
version = {attr = "just_mospec.__version__"}

[tool.coverage.run]
relative_files = true
source = ["py/just_mospec"]
omit = ["py/just_mospec/_version.py",
        "py/just_mospec/conftest*",
        "py/just_mospec/test/*",
        "*/just_mospec/_version.py",
        "*/just_mospec/conftest*",
        "*/just_mospec/test/*"]

[tool.coverage.report]
exclude_lines = [
                "pragma: no cover",
                "except ImportError",
                "raise AssertionError",
                "raise NotImplementedError",
                "def main\\(.*\\):",
                "pragma: py{ignore_python_version}",
                "def _ipython_key_completions_",
                ]
